-- Seed birding locations around the world

INSERT INTO locations (name, country, country_code, region, habitat_type, latitude, longitude, best_season, description, icon) VALUES
('Everglades National Park', 'United States', 'us', 'Florida', 'WETLAND', 25.286700, -80.898700, 'Dry season, December to April', 'A vast subtropical wetland of sawgrass marshes and mangrove forests, home to wading birds, raptors and the elusive Snail Kite.', '💧'),
('Yellowstone National Park', 'United States', 'us', 'Wyoming', 'MOUNTAIN', 44.428000, -110.588000, 'Late spring to early fall', 'Geothermal valleys, rivers and forested mountains supporting eagles, owls, swans and abundant migratory songbirds.', '⛰️'),
('Central Park', 'United States', 'us', 'New York', 'URBAN_PARK', 40.785091, -73.968285, 'Spring and fall migration', 'An 843-acre green oasis in Manhattan that acts as a critical stopover for migrating songbirds along the Atlantic Flyway.', '🏙️'),
('Pantanal Wetlands', 'Brazil', 'br', 'Mato Grosso', 'WETLAND', -17.683300, -57.166700, 'Dry season, July to October', 'The world''s largest tropical wetland, teeming with macaws, herons, storks and one of the densest concentrations of birdlife on Earth.', '💧'),
('Manu National Park', 'Peru', 'pe', 'Madre de Dios', 'FOREST', -12.183300, -71.400000, 'Dry season, May to October', 'A UNESCO biosphere reserve spanning Andean cloud forest to Amazon lowlands, with one of the highest bird diversity counts of any park on the planet.', '🌲'),
('Serengeti National Park', 'Tanzania', 'tz', 'Mara Region', 'GRASSLAND', -2.333300, 34.833300, 'Dry season, June to October', 'Endless savanna grassland famous for the Great Migration, also home to ostriches, secretarybirds and countless raptors.', '🌾'),
('Okavango Delta', 'Botswana', 'bw', 'North-West District', 'WETLAND', -19.283300, 22.900000, 'Flood season, June to August', 'A lush inland river delta in the Kalahari that bursts with herons, kingfishers, jacanas and fish eagles when the floodwaters arrive.', '💧'),
('Galápagos Islands', 'Ecuador', 'ec', 'Galápagos Province', 'COASTAL', -0.953600, -90.965500, 'Year-round, cooler season June to December', 'A volcanic archipelago of fearless wildlife, including blue-footed boobies, penguins and frigatebirds found nowhere else on Earth.', '🌊'),
('Wadden Sea', 'Netherlands', 'nl', 'Friesland', 'COASTAL', 53.350000, 5.500000, 'Spring and autumn migration', 'A UNESCO World Heritage tidal flat ecosystem along the North Sea coast, hosting millions of migratory shorebirds and starling murmurations.', '🌊'),
('Cairngorms National Park', 'United Kingdom', 'gb', 'Scotland', 'MOUNTAIN', 57.083300, -3.666700, 'Late spring to early summer', 'Britain''s largest national park, with ancient pine forests and high plateaus that shelter golden eagles, ptarmigan and ospreys.', '⛰️'),
('Camargue Regional Park', 'France', 'fr', 'Provence-Alpes-Côte d''Azur', 'WETLAND', 43.500000, 4.633300, 'Spring through early summer', 'A Rhône delta of salt pans and lagoons famous for pink flamingos, herons and a dazzling array of waterfowl.', '💧'),
('Doñana National Park', 'Spain', 'es', 'Andalusia', 'WETLAND', 37.000000, -6.433300, 'Spring migration, March to May', 'A mosaic of marshes, dunes and Mediterranean scrub at the mouth of the Guadalquivir, a critical refuge for migratory waterbirds.', '💧'),
('Keoladeo National Park', 'India', 'in', 'Rajasthan', 'WETLAND', 27.160000, 77.520000, 'Winter, October to February', 'A former royal hunting reserve turned wetland sanctuary, drawing tens of thousands of migratory waterfowl and storks each winter.', '💧'),
('Kakadu National Park', 'Australia', 'au', 'Northern Territory', 'FOREST', -12.850000, 132.833300, 'Dry season, May to October', 'A vast tropical reserve of wetlands, woodlands and sandstone escarpments supporting over a third of Australia''s bird species.', '🌲'),
('Fiordland National Park', 'New Zealand', 'nz', 'Southland', 'FOREST', -45.416700, 167.716700, 'Summer, December to February', 'Remote temperate rainforest and fjords sheltering rare flightless birds and alpine parrots found only in New Zealand.', '🌲'),
('Lake Mývatn', 'Iceland', 'is', 'Northeastern Region', 'TUNDRA', 65.600000, -17.000000, 'Summer, June to August', 'A volcanic lake and wetland complex with one of the highest densities of breeding ducks anywhere in the world.', '❄️'),
('Monteverde Cloud Forest', 'Costa Rica', 'cr', 'Puntarenas', 'FOREST', 10.300000, -84.800000, 'Dry season, December to April', 'Misty montane cloud forest renowned for the Resplendent Quetzal, hummingbirds and an explosion of neotropical color.', '🌲'),
('Atacama Salt Flats', 'Chile', 'cl', 'Antofagasta', 'DESERT', -23.500000, -68.250000, 'Year-round, best at sunrise', 'High-altitude salt pans in the driest desert on Earth, where flocks of flamingos feed in shallow brine lagoons.', '🏜️');
